swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/transactionsChecking:
    get:
      tags:
        - User transactions Checking
      summary: TransactionsChecking
      description: Returns all transactions
      responses:
        "200":
          description: Returns an array of all transactions
          schema:
            $ref: "#/definitions/BankResponse"
        "400":
          description: Invalid Fields
  /user/transactionsCheckingCurrentMonth:
    get:
      tags:
        - User transactions Checking
      summary: TransactionsChecking
      description: Returns all transactions for the current month
      responses:
        "200":
          description: Returns an array of all transactions for the current month
          schema:
            $ref: "#/definitions/BankResponse"
        "400":
          description: Invalid Fields
  /user/transactionsChecking/{id}/category:
    patch:
      security:
        - Bearer: []
      tags:
        - User transactions Checking
      summary: Update Transaction Category
      description: Update the category of a transaction by ID
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: id
          in: path
          description: ID of the transaction to update
          required: true
          type: integer
        - in: body
          name: body
          description: New category for the transaction
          required: true
          schema:
            type: object
            properties:
              category:
                type: string
      responses:
        "200":
          description: Transaction category updated successfully
          schema:
            type: object
            properties:
              category:
                type: string
        "400":
          description: Invalid Fields
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
  /user/transactionsChecking/{id}/note:
    patch:
      security:
        - Bearer: []
      tags:
        - User transactions Checking
      summary: Update Transaction note
      description: Update the note of a transaction by ID
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: id
          in: path
          description: ID of the transaction to update
          required: true
          type: integer
        - in: body
          name: body
          description: New note for the transaction
          required: true
          schema:
            type: object
            properties:
              note:
                type: string
      responses:
        "200":
          description: Transaction note updated successfully
          schema:
            type: object
            properties:
              note:
                type: string
        "400":
          description: Invalid Fields
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
  /user/transactionsSavings:
    get:
      tags:
        - User transactions Savings
      summary: TransactionsSavings
      description: Returns all transactions
      responses:
        "200":
          description: Returns an array of all transactions
          schema:
            $ref: "#/definitions/BankResponse"
        "400":
          description: Invalid Fields
  /user/transactionsSavingsCurrentMonth:
    get:
      tags:
        - User transactions Savings
      summary: TransactionsSavings
      description: Returns all transactions for the current month
      responses:
        "200":
          description: Returns an array of all transactions for the current month
          schema:
            $ref: "#/definitions/BankResponse"
        "400":
          description: Invalid Fields
  /user/transactionsSavings/{id}/category:
    patch:
      security:
        - Bearer: []
      tags:
        - User transactions Savings
      summary: Update Transaction Category
      description: Update the category of a transaction by ID
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: id
          in: path
          description: ID of the transaction to update
          required: true
          type: integer
        - in: body
          name: body
          description: New category for the transaction
          required: true
          schema:
            type: object
            properties:
              category:
                type: string
      responses:
        "200":
          description: Transaction category updated successfully
          schema:
            type: object
            properties:
              category:
                type: string
        "400":
          description: Invalid Fields
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
  /user/transactionsSavings/{id}/note:
    patch:
      security:
        - Bearer: []
      tags:
        - User transactions Savings
      summary: Update Transaction note
      description: Update the note of a transaction by ID
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: id
          in: path
          description: ID of the transaction to update
          required: true
          type: integer
        - in: body
          name: body
          description: New note for the transaction
          required: true
          schema:
            type: object
            properties:
              note:
                type: string
      responses:
        "200":
          description: Transaction note updated successfully
          schema:
            type: object
            properties:
              note:
                type: string
        "400":
          description: Invalid Fields
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
  /user/transactionsCreditCard:
    get:
      tags:
        - User transactions Credit Card
      summary: TransactionsCredit Card
      description: Returns all transactions
      responses:
        "200":
          description: Returns an array of all transactions
          schema:
            $ref: "#/definitions/BankResponse"
        "400":
          description: Invalid Fields
  /user/transactionsCreditCardCurrentMonth:
    get:
      tags:
        - User transactions Credit Card
      summary: TransactionsCredit Card
      description: Returns all transactions for the current month
      responses:
        "200":
          description: Returns an array of all transactions for the current month
          schema:
            $ref: "#/definitions/BankResponse"
        "400":
          description: Invalid Fields
  /user/transactionsCreditCard/{id}/category:
    patch:
      security:
        - Bearer: []
      tags:
        - User transactions Credit Card
      summary: Update Transaction Category
      description: Update the category of a transaction by ID
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: id
          in: path
          description: ID of the transaction to update
          required: true
          type: integer
        - in: body
          name: body
          description: New category for the transaction
          required: true
          schema:
            type: object
            properties:
              category:
                type: string
      responses:
        "200":
          description: Transaction category updated successfully
          schema:
            type: object
            properties:
              category:
                type: string
        "400":
          description: Invalid Fields
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
  /user/transactionsCreditCard/{id}/note:
    patch:
      security:
        - Bearer: []
      tags:
        - User transactions Credit Card
      summary: Update Transaction note
      description: Update the note of a transaction by ID
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: id
          in: path
          description: ID of the transaction to update
          required: true
          type: integer
        - in: body
          name: body
          description: New note for the transaction
          required: true
          schema:
            type: object
            properties:
              note:
                type: string
      responses:
        "200":
          description: Transaction note updated successfully
          schema:
            type: object
            properties:
              note:
                type: string
        "400":
          description: Invalid Fields
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  BankResponse:
    type: object
    properties:
      transactions:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
            date:
              type: string
              format: date-time
            amount:
              type: integer
            description:
              type: string
            category:
              type: string
            balance:
              type: integer
            transaction_type:
              type: string
            note:
              type: string
